/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrator
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import database.HotelDBManager;
import Project2.CustomerManager;
import Project2.Customers;



public class MainMenu extends javax.swing.JFrame {
    
    private String fullName; // 💡 Stores the current user's name
    
    

    /**
     * Creates new form MainMenu
     */
     public MainMenu(String fullName) {
       this.fullName = fullName;
       initComponents();
       greetingLabel.setText("Greetings, " + fullName);

       // Load personal info
        CustomerManager cm = new CustomerManager();
        Customers customer = cm.getCustomerByFullName(fullName);
        if (customer != null) {
            DefaultTableModel personalModel = (DefaultTableModel) personalInfo.getModel();
            personalModel.setRowCount(0);
            personalModel.addRow(new Object[] {
                customer.getFullName(),
                customer.getEmail(),
                customer.getPhoneNumber()
            });
        }

        // Load bookings
        try {
            Connection conn = new HotelDBManager().getConnection();
            String sql = "SELECT ROOMNO, ROOMTYPE, CHECKINDATE, CHECKOUTDATE " +
                         "FROM HOTELBOOKINGMANAGEMENTDB WHERE FULL_NAME = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, fullName);
            ResultSet rs = stmt.executeQuery();

            DefaultTableModel bookingModel = (DefaultTableModel) viewBookings.getModel();
            bookingModel.setRowCount(0);

            while (rs.next()) {
                int roomNo = rs.getInt("ROOMNO");
                String roomType = rs.getString("ROOMTYPE");
                String checkIn = rs.getString("CHECKINDATE");
                String checkOut = rs.getString("CHECKOUTDATE");

                bookingModel.addRow(new Object[] {
                    fullName, roomNo, roomType, checkIn, checkOut
                });
            }

            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Default constructor (optional, fallback if needed)
    public MainMenu() {
        initComponents();
        greetingLabel.setText("Greetings, Guest");
    }

    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Logout = new javax.swing.JButton();
        CancelBooking = new javax.swing.JButton();
        BookRoom = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        greetingLabel = new javax.swing.JLabel();
        UpdateFullName = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewBookings = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        personalInfo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logout.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Logout.setText("Log Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jPanel2.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 104, 217, 187));

        CancelBooking.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        CancelBooking.setText("<html><center>Cancel<br>Booking</center></html>\n");
        CancelBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBookingActionPerformed(evt);
            }
        });
        jPanel2.add(CancelBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 107, 217, 187));

        BookRoom.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        BookRoom.setText("<html><center>Book<br>a Room</center></html>\n\n");
        BookRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookRoomActionPerformed(evt);
            }
        });
        jPanel2.add(BookRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 107, 217, 187));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        greetingLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        greetingLabel.setForeground(new java.awt.Color(255, 255, 255));
        greetingLabel.setText("Greetings,  ");

        UpdateFullName.setBackground(new java.awt.Color(0, 51, 102));
        UpdateFullName.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        UpdateFullName.setForeground(new java.awt.Color(255, 255, 255));
        UpdateFullName.setText("Update Your Information");
        UpdateFullName.setBorder(null);
        UpdateFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateFullNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(greetingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(UpdateFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greetingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(UpdateFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 910, 60));

        jTabbedPane1.setBackground(new java.awt.Color(0, 102, 153));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));

        viewBookings.setBackground(new java.awt.Color(0, 102, 153));
        viewBookings.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        viewBookings.setForeground(new java.awt.Color(255, 255, 255));
        viewBookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Full Name", "Room Number", "Room Type", "Check In", "Check Out"
            }
        ));
        viewBookings.setGridColor(new java.awt.Color(0, 102, 153));
        viewBookings.setSelectionBackground(new java.awt.Color(0, 102, 153));
        viewBookings.setSelectionForeground(new java.awt.Color(0, 102, 153));
        jScrollPane1.setViewportView(viewBookings);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("View Your Bookings", jPanel4);

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        personalInfo.setBackground(new java.awt.Color(0, 102, 153));
        personalInfo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        personalInfo.setForeground(new java.awt.Color(255, 255, 255));
        personalInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Full Name", "Email", "Phone Number"
            }
        ));
        jScrollPane2.setViewportView(personalInfo);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Personal Information", jPanel3);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 910, 380));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateFullNameActionPerformed
        // Create and show the UpdatedInfo window
        UpdatedInfo updatedInfoWindow = new UpdatedInfo();
        updatedInfoWindow.setVisible(true);

        // Optional: close or hide the current window
        this.dispose();  // closes current window
    }//GEN-LAST:event_UpdateFullNameActionPerformed

    private void CancelBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBookingActionPerformed
        CancelBooking cancelBookingWindow = new CancelBooking();
        cancelBookingWindow.setVisible(true);
        cancelBookingWindow.setLocationRelativeTo(null); // Center it
        this.dispose(); // Close current window
    }//GEN-LAST:event_CancelBookingActionPerformed

    private void BookRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookRoomActionPerformed
        BookARoom bookRoomWindow = new BookARoom(fullName); // ✅ Pass the user's name
        bookRoomWindow.setVisible(true);
        bookRoomWindow.setLocationRelativeTo(null); // Center it
        this.dispose(); // Close current window
    }//GEN-LAST:event_BookRoomActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        LoginForm loginWindow = new LoginForm();
        loginWindow.setVisible(true);
        loginWindow.setLocationRelativeTo(null); // Center it
        this.dispose(); // Close current window
    }//GEN-LAST:event_LogoutActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new MainMenu("Kyle Elmo").setVisible(true); // You can replace "Guest" with any name for testing
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookRoom;
    private javax.swing.JButton CancelBooking;
    private javax.swing.JButton Logout;
    private javax.swing.JButton UpdateFullName;
    private javax.swing.JLabel greetingLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable personalInfo;
    private javax.swing.JTable viewBookings;
    // End of variables declaration//GEN-END:variables
}
